### ISSUE TITLE
`P256_mulmod` multiplication method

### ISSUE THREAD

**Issue by svenhofman** [Emill/P256-Cortex-M4#3]
Hi Emill,

I've been studying your implementation and was wondering what the exact method is called with which you perform the multiplication in the first part of `P256_mulmod`. I've been looking at some papers explaining different methods (e.g. operand/product/hybrid scanning) but I can't seem to find the method you are using. It seems like you are performing a hybrid between the operand and product method, since you are first performing multiplication of the lower 4 words of B with all the words of A, and then continuing with the other words in B and doing the same. Do you have a reference (or name) for it?

Thanks in advance!

**Comment by Emill** [comment]
Hi Sven,

I personally don't call this method anything particular. I just made the observation that splitting one operand into two part results in fewer register spills.

If the "hybrid" method you refer to is the one described in https://www.iacr.org/archive/ches2004/31560117/31560117.pdf, it's not exactly the same, as that also seems to split the second operand too into two (or more) parts. 

If you would like more details on this topic, I can send you a paper I prepared but unfortunately not yet have had time to publish.

**Comment by svenhofman** [comment]
Hi,

I found your method to be similar to https://eprint.iacr.org/2020/410.pdf, Fig. 7, although it isn't exactly the same. I'd be interested in the paper!

**Comment by Emill** [comment]
Ok, just sent you an email.

**Comment by Acccrypto** [comment]
Hi, Emill,

I think your work is excellent. The Montgomery reduction implemented by assembly language is quite efficient.  I wonder the principle of this reduction for the modulus p. How can it avoid an multiplication inside the classic Montgomery reduction algorithm? Instead, it uses some addition and subtraction instructions.

Thanks in advance!

**Comment by Emill** [comment]
@Acccrypto please see section 3.1.2 of https://eprint.iacr.org/2021/1151 for a description. The loop is unrolled and the instructions are reordered in a way to create as long add-with-carry chains as possible (since saving and restoring the carry flag costs instructions), while still trying to minimise register usage in order to not have to spill and restore to the stack more than necessary.

**Comment by Acccrypto** [comment]
Thank you very much for your kindly reply. Now I understand the method.
